# Generated by Django 6.0.3 on 2026-03-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed')], max_length=20)),
                ('lyrics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('link_id', models.UUIDField(primary_key=True, serialize=False)),
                ('public_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('format', models.CharField(default='MP3', max_length=10)),
                ('size_in_mb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('voice_type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField()),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='music.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.user'),
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('task_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'TimedOut')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('retry_count', models.IntegerField(default=0)),
                ('backgrounded', models.BooleanField(default=False)),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_task', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='music.user')),
            ],
        ),
    ]
