# Generated by Django 6.0.3 on 2026-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='external_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
